### ISSUE TITLE
Install emacs 23 can fix the problem

### ISSUE THREAD

**Issue by WangLeshan** [saccohuo/org2wiz#1]
I met the same problem as you mentioned in your README.org file, and fixed it by another way.
## The solution

As the author myflocry said in http://bbs.wiz.cn/thread-17135-1-1.html,

> 测试过的环境:
> winxp 32bit; ie6; wiz 32bit 3.3.25; emacs 23; mathjax 2.1
> win7 64bit; ie8-9; wiz 32bit 3.3.25; emacs 23; mathjax 2.1
> 
> 安装Emacs，下载gnu emacs 22以后版本，最好是23。下载地址为：http://ftp.gnu.org/gnu/emacs/windows/

The author tested the plugin by  emacs 23, and recommended Emacs 23 .

One can download emacs-23.4-bin-i386.zip from http://mirrors.hust.edu.cn/gnu/windows/emacs
## New problem by the method of modify Org-Mode.js

In fact your method originally from 
[http://bbs.wiz.cn/forum.php?mod=viewthread&tid=17135&page=7#pid109573](url)
and it brings a side effect in my win 8.1 with Emacs 24.4, that is, it can not refresh the export html file in wiznote immediately. I had to open another note and open the org note again. 
So take the lesser of two evils, I use Emacs 23 for the plugin follows the installation guide by the author myflocry.

**Comment by FelixHuoEZ** [comment]
Soga, I am a emacser, so emacs version means a lot for me.

I use Emacs 24.5 now and Windows 7 x64, but I did not encounter the problem you said. So I doubt that is a problem of Windows 8.

Sorry for not refered the link of this solution to README file, I will modify it right now. 
Thanks for your reminder!

**Comment by saccohuo** [comment]
#8f135941cfa68b4f95f423fcaa8fdf4b1a8e5977
