### ISSUE TITLE
我在安装这个插件时，所遇到的问题

### ISSUE THREAD

**Issue by colorfulsky** [saccohuo/org2wiz#2]
下载zip包后，改名安装失败。
![image](https://cloud.githubusercontent.com/assets/11696388/18864630/d1a9d05a-84c9-11e6-9723-cc9741f57ad7.png)

**Comment by colorfulsky** [comment]
## 现在问题已经解决

直接clone相关repo，放在相对应的插件目录，重启即可。
![image](https://cloud.githubusercontent.com/assets/11696388/18865223/aa0e4082-84cc-11e6-9b7c-e2cd59467c3d.png)
![image](https://cloud.githubusercontent.com/assets/11696388/18865224/aa625514-84cc-11e6-86e3-0b551ca7f943.png)

**Comment by FelixHuoEZ** [comment]
其实我在release里面有有放一个wizplugin后缀的文件，直接下载安装即可。
