### ISSUE TITLE
插件是否有计划支持4.4版本以后的为知笔记？

### ISSUE THREAD

**Issue by colorfulsky** [saccohuo/org2wiz#3]
在用最新的为知笔记，同时是emacs重度用户。如果有支持计划，那最好。没有的话，可能会回退版本。（果然对emacs是真爱啊）

**Comment by FelixHuoEZ** [comment]
已经支持了，可以直接在 [Releases](https://github.com/saccohuo/org2wiz/releases) 中下载。
最近正在添加新功能，还有个bug没解决掉，解决掉会再发布加入了新功能的版本。
如果有兴趣，也可以到 develop 分支里面打包尝鲜，只是暂时需要手动修改 options.ini 文件。另外还需要安装有 Python 3。

**Comment by FelixHuoEZ** [comment]
现在只剩下“设置选项”的bug了，需要在3秒内完成设置，考验手速的时候到了。直接到 Releases 中下载。
不要求安装有Python。

**Comment by colorfulsky** [comment]
好的，感谢。这个插件对我来说很重要，加之只是简单导出到为知笔记，功能对我来说已然足够。后面我用的过程中发现什么问题再来报告。再次感谢开发 :smile:
